# Generated by Django 4.2.13 on 2024-05-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uDept', models.CharField(max_length=50)),
                ('uFunction', models.CharField(max_length=50)),
                ('uPosition', models.CharField(max_length=50)),
                ('uVietnameseName', models.CharField(max_length=50)),
                ('uChineseName', models.CharField(max_length=50)),
                ('uEnglishName', models.CharField(max_length=50)),
                ('uLevel', models.CharField(max_length=50)),
                ('uBirthday', models.CharField(max_length=50)),
                ('uGender', models.CharField(max_length=50)),
                ('uAddress', models.CharField(max_length=50)),
                ('uUniversity', models.CharField(max_length=50)),
                ('uMajor', models.CharField(max_length=50)),
                ('uExperience', models.CharField(max_length=50)),
                ('uLastCompany', models.CharField(max_length=50)),
                ('uMail', models.CharField(max_length=50)),
                ('uPhone', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
