# Generated by Django 4.2.13 on 2024-05-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_swmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swmember',
            name='userID',
            field=models.CharField(max_length=10),
        ),
    ]
